# Generated by Django 4.2.17 on 2025-02-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='salary_range',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
