# Generated by Django 4.2.17 on 2025-03-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0002_jobseeker_salary_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='renewal_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
