# Generated by Django 4.2.17 on 2025-03-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0005_alter_jobseeker_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='District',
            new_name='district',
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='education_level',
            field=models.CharField(choices=[('none', 'No Formal Education'), ('primary', 'Primary Education'), ('ordinary_level', 'Ordinary Level'), ('advanced_diploma', 'Advanced Diploma'), ('secondary', 'Secondary Education'), ('vocational', 'Vocational Training'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD')], default='none', max_length=20),
        ),
    ]
