# Generated by Django 4.2.17 on 2025-08-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0006_rename_district_jobseeker_district_and_more'),
        ('job_seeker', 'xxx_enhance_skiils_field'),
    ]

    operations = [
    ]
