# Generated by Django 4.2.17 on 2025-08-26 20:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0007_merge_20250826_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='experience',
            field=models.IntegerField(default=0, help_text='Overall years of experience'),
        ),
        migrations.CreateModel(
            name='JobSeekerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('experience_level', models.CharField(help_text="e.g., '0-1', '1-3', '3-5', '5-8', '8+'", max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_skills', to='job_seeker.jobseeker')),
            ],
            options={
                'unique_together': {('job_seeker', 'skill_name')},
            },
        ),
    ]
