# Generated by Django 4.2.17 on 2025-08-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0008_alter_jobseeker_experience_jobseekerskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='skills_old',
            field=models.TextField(blank=True, default='', help_text='Deprecated: Comma-separated skills'),
        ),
    ]
