# Generated by Django 4.2.17 on 2025-08-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0009_alter_jobseeker_skills_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='skills_old',
            field=models.TextField(blank=True, help_text='Deprecated: Comma-separated skills', null=True),
        ),
    ]
