# Generated by Django 4.2.17 on 2025-08-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0010_alter_jobseeker_skills_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='experience',
            field=models.IntegerField(default=0, help_text='Overall years of experience (auto-calculated)'),
        ),
    ]
