# Generated by Django 4.2.17 on 2025-02-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='offer_type',
            field=models.CharField(choices=[('company', 'Company'), ('individual', 'Individual')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
