# Generated by Django 4.2.17 on 2025-02-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offer_app', '0003_joboffer_job_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry Level'), ('intermediate', 'Intermediate'), ('mid', 'Mid Level'), ('senior or executive', 'Senior or Executive Level')], max_length=20),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='responsibilities',
            field=models.JSONField(default=list),
        ),
    ]
