# Generated by Django 4.2.17 on 2025-02-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('job_seeker', 'Job Seeker'), ('job_offer', 'Job Offer')], max_length=20),
        ),
    ]
