# Generated by Django 4.2.17 on 2025-02-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('closed', 'Closed')], default='waiting', max_length=10),
        ),
    ]
