# Generated by Django 4.2.17 on 2025-03-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisementApp', '0002_alter_advertisement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
    ]
